/**
 * generated by Xtext 2.23.0.M3
 */
package org.xtext.example.landingpagedsl.generator;

import com.google.common.collect.Iterables;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.example.landingpagedsl.lPDSL.PageHeader;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class LPDSLGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    Iterable<PageHeader> _filter = Iterables.<PageHeader>filter(IteratorExtensions.<EObject>toIterable(resource.getAllContents()), PageHeader.class);
    for (final PageHeader e : _filter) {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("<!DOCTYPE html>");
      _builder.newLine();
      _builder.append("<html lang=\"en\">");
      _builder.newLine();
      _builder.newLine();
      _builder.append("<head>");
      _builder.newLine();
      _builder.append("  ");
      _builder.append("<meta name=\"Generated Landing Page\" content=\"This is a personal landing page generated by Web-Modeler\" />");
      _builder.newLine();
      _builder.append("  ");
      _builder.append("<meta charset=\"utf-8\">");
      _builder.newLine();
      _builder.append("  ");
      _builder.append("<title>");
      String _string = e.getName().toString();
      _builder.append(_string, "  ");
      _builder.append("</title>");
      _builder.newLineIfNotEmpty();
      _builder.append("  ");
      _builder.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
      _builder.newLine();
      _builder.append("  ");
      _builder.append("<meta name=\"author\" content=\"\">");
      _builder.newLine();
      _builder.append("  ");
      _builder.append("<link rel=\"stylesheet\" href=\"css/style.css\">");
      _builder.newLine();
      _builder.append("  ");
      _builder.append("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>");
      _builder.newLine();
      _builder.append("</head>");
      _builder.newLine();
      _builder.append("<body>");
      _builder.newLine();
      _builder.append("  ");
      _builder.newLine();
      _builder.append("<div class=\"container\">");
      _builder.newLine();
      _builder.append("  ");
      _builder.newLine();
      _builder.append("</div>");
      _builder.newLine();
      _builder.newLine();
      _builder.append("<script>");
      _builder.newLine();
      _builder.append("</script>");
      _builder.newLine();
      _builder.newLine();
      _builder.append("</body>");
      _builder.newLine();
      _builder.append("</html>");
      fsa.generateFile("huh.html", _builder);
    }
  }
}
