/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.landingpagedsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.landingpagedsl.ui.internal.LandingpagedslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LPDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(LandingpagedslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		LandingpagedslActivator activator = LandingpagedslActivator.getInstance();
		return activator != null ? activator.getInjector(LandingpagedslActivator.ORG_XTEXT_EXAMPLE_LANDINGPAGEDSL_LPDSL) : null;
	}

}
