/*
 * generated by Xtext 2.23.0.M3
 */
package org.xtext.example.landingpagedsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LPDSLRuntimeModule extends AbstractLPDSLRuntimeModule {
}
