/*
 * generated by Xtext 2.23.0.M3
 */
package org.xtext.example.landingpagedsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LPDSLStandaloneSetup extends LPDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new LPDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
