/**
 * generated by Xtext 2.23.0.M3
 */
package org.xtext.example.landingpagedsl.lPDSL.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.landingpagedsl.lPDSL.AboutMe;
import org.xtext.example.landingpagedsl.lPDSL.Items;
import org.xtext.example.landingpagedsl.lPDSL.LPDSLPackage;
import org.xtext.example.landingpagedsl.lPDSL.Picture;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>About Me</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.landingpagedsl.lPDSL.impl.AboutMeImpl#getPicture <em>Picture</em>}</li>
 *   <li>{@link org.xtext.example.landingpagedsl.lPDSL.impl.AboutMeImpl#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AboutMeImpl extends SectionsImpl implements AboutMe
{
  /**
   * The cached value of the '{@link #getPicture() <em>Picture</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPicture()
   * @generated
   * @ordered
   */
  protected EList<Picture> picture;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected EList<Items> description;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AboutMeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LPDSLPackage.Literals.ABOUT_ME;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Picture> getPicture()
  {
    if (picture == null)
    {
      picture = new EObjectContainmentEList<Picture>(Picture.class, this, LPDSLPackage.ABOUT_ME__PICTURE);
    }
    return picture;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Items> getDescription()
  {
    if (description == null)
    {
      description = new EObjectContainmentEList<Items>(Items.class, this, LPDSLPackage.ABOUT_ME__DESCRIPTION);
    }
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LPDSLPackage.ABOUT_ME__PICTURE:
        return ((InternalEList<?>)getPicture()).basicRemove(otherEnd, msgs);
      case LPDSLPackage.ABOUT_ME__DESCRIPTION:
        return ((InternalEList<?>)getDescription()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LPDSLPackage.ABOUT_ME__PICTURE:
        return getPicture();
      case LPDSLPackage.ABOUT_ME__DESCRIPTION:
        return getDescription();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LPDSLPackage.ABOUT_ME__PICTURE:
        getPicture().clear();
        getPicture().addAll((Collection<? extends Picture>)newValue);
        return;
      case LPDSLPackage.ABOUT_ME__DESCRIPTION:
        getDescription().clear();
        getDescription().addAll((Collection<? extends Items>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LPDSLPackage.ABOUT_ME__PICTURE:
        getPicture().clear();
        return;
      case LPDSLPackage.ABOUT_ME__DESCRIPTION:
        getDescription().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LPDSLPackage.ABOUT_ME__PICTURE:
        return picture != null && !picture.isEmpty();
      case LPDSLPackage.ABOUT_ME__DESCRIPTION:
        return description != null && !description.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //AboutMeImpl
