/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.landingpagedsl.lPDSL.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.landingpagedsl.lPDSL.AboutMe;
import org.xtext.example.landingpagedsl.lPDSL.ContactInformation;
import org.xtext.example.landingpagedsl.lPDSL.Description;
import org.xtext.example.landingpagedsl.lPDSL.ImagePath;
import org.xtext.example.landingpagedsl.lPDSL.Items;
import org.xtext.example.landingpagedsl.lPDSL.LPDSLFactory;
import org.xtext.example.landingpagedsl.lPDSL.LPDSLPackage;
import org.xtext.example.landingpagedsl.lPDSL.LandingPage;
import org.xtext.example.landingpagedsl.lPDSL.LinkItem;
import org.xtext.example.landingpagedsl.lPDSL.Links;
import org.xtext.example.landingpagedsl.lPDSL.PageBody;
import org.xtext.example.landingpagedsl.lPDSL.PageComponent;
import org.xtext.example.landingpagedsl.lPDSL.PageFooter;
import org.xtext.example.landingpagedsl.lPDSL.PageHeader;
import org.xtext.example.landingpagedsl.lPDSL.Picture;
import org.xtext.example.landingpagedsl.lPDSL.PictureCarousel;
import org.xtext.example.landingpagedsl.lPDSL.QualifiedPath;
import org.xtext.example.landingpagedsl.lPDSL.Resume;
import org.xtext.example.landingpagedsl.lPDSL.Sections;
import org.xtext.example.landingpagedsl.lPDSL.TabItems;
import org.xtext.example.landingpagedsl.lPDSL.TimeSpecifier;
import org.xtext.example.landingpagedsl.lPDSL.URL;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class LPDSLFactoryImpl extends EFactoryImpl implements LPDSLFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static LPDSLFactory init()
  {
    try
    {
      LPDSLFactory theLPDSLFactory = (LPDSLFactory)EPackage.Registry.INSTANCE.getEFactory(LPDSLPackage.eNS_URI);
      if (theLPDSLFactory != null)
      {
        return theLPDSLFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new LPDSLFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LPDSLFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case LPDSLPackage.LANDING_PAGE: return createLandingPage();
      case LPDSLPackage.PAGE_COMPONENT: return createPageComponent();
      case LPDSLPackage.PICTURE_CAROUSEL: return createPictureCarousel();
      case LPDSLPackage.PAGE_FOOTER: return createPageFooter();
      case LPDSLPackage.LINK_ITEM: return createLinkItem();
      case LPDSLPackage.URL: return createURL();
      case LPDSLPackage.QUALIFIED_PATH: return createQualifiedPath();
      case LPDSLPackage.PAGE_HEADER: return createPageHeader();
      case LPDSLPackage.TAB_ITEMS: return createTabItems();
      case LPDSLPackage.PAGE_BODY: return createPageBody();
      case LPDSLPackage.SECTIONS: return createSections();
      case LPDSLPackage.LINKS: return createLinks();
      case LPDSLPackage.CONTACT_INFORMATION: return createContactInformation();
      case LPDSLPackage.RESUME: return createResume();
      case LPDSLPackage.ITEMS: return createItems();
      case LPDSLPackage.DESCRIPTION: return createDescription();
      case LPDSLPackage.TIME_SPECIFIER: return createTimeSpecifier();
      case LPDSLPackage.INTEGER: return createInteger();
      case LPDSLPackage.ABOUT_ME: return createAboutMe();
      case LPDSLPackage.PICTURE: return createPicture();
      case LPDSLPackage.IMAGE_PATH: return createImagePath();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LandingPage createLandingPage()
  {
    LandingPageImpl landingPage = new LandingPageImpl();
    return landingPage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PageComponent createPageComponent()
  {
    PageComponentImpl pageComponent = new PageComponentImpl();
    return pageComponent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PictureCarousel createPictureCarousel()
  {
    PictureCarouselImpl pictureCarousel = new PictureCarouselImpl();
    return pictureCarousel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PageFooter createPageFooter()
  {
    PageFooterImpl pageFooter = new PageFooterImpl();
    return pageFooter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LinkItem createLinkItem()
  {
    LinkItemImpl linkItem = new LinkItemImpl();
    return linkItem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public URL createURL()
  {
    URLImpl url = new URLImpl();
    return url;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QualifiedPath createQualifiedPath()
  {
    QualifiedPathImpl qualifiedPath = new QualifiedPathImpl();
    return qualifiedPath;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PageHeader createPageHeader()
  {
    PageHeaderImpl pageHeader = new PageHeaderImpl();
    return pageHeader;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TabItems createTabItems()
  {
    TabItemsImpl tabItems = new TabItemsImpl();
    return tabItems;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PageBody createPageBody()
  {
    PageBodyImpl pageBody = new PageBodyImpl();
    return pageBody;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Sections createSections()
  {
    SectionsImpl sections = new SectionsImpl();
    return sections;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Links createLinks()
  {
    LinksImpl links = new LinksImpl();
    return links;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ContactInformation createContactInformation()
  {
    ContactInformationImpl contactInformation = new ContactInformationImpl();
    return contactInformation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Resume createResume()
  {
    ResumeImpl resume = new ResumeImpl();
    return resume;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Items createItems()
  {
    ItemsImpl items = new ItemsImpl();
    return items;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Description createDescription()
  {
    DescriptionImpl description = new DescriptionImpl();
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TimeSpecifier createTimeSpecifier()
  {
    TimeSpecifierImpl timeSpecifier = new TimeSpecifierImpl();
    return timeSpecifier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public org.xtext.example.landingpagedsl.lPDSL.Integer createInteger()
  {
    IntegerImpl integer = new IntegerImpl();
    return integer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AboutMe createAboutMe()
  {
    AboutMeImpl aboutMe = new AboutMeImpl();
    return aboutMe;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Picture createPicture()
  {
    PictureImpl picture = new PictureImpl();
    return picture;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImagePath createImagePath()
  {
    ImagePathImpl imagePath = new ImagePathImpl();
    return imagePath;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LPDSLPackage getLPDSLPackage()
  {
    return (LPDSLPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static LPDSLPackage getPackage()
  {
    return LPDSLPackage.eINSTANCE;
  }

} //LPDSLFactoryImpl
