/*
 * generated by Xtext 2.23.0.M3
 */
package org.xtext.example.landingpagedsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLPDSLScopeProvider extends DelegatingScopeProvider {
}
