/*
 * generated by Xtext 2.23.0.M3
 */
package org.xtext.example.landingpagedsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.landingpagedsl.ui.internal.LandingpagedslActivator;

public class LPDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LandingpagedslActivator.getInstance().getInjector("org.xtext.example.landingpagedsl.LPDSL");
	}

}
