/*
 * generated by Xtext 2.23.0.M3
 */
package org.xtext.example.landingpagedsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.landingpagedsl.LPDSLRuntimeModule;
import org.xtext.example.landingpagedsl.LPDSLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LPDSLIdeSetup extends LPDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LPDSLRuntimeModule(), new LPDSLIdeModule()));
	}
	
}
