/*
 * generated by Xtext 2.23.0.M3
 */
package org.xtext.example.landingpagedsl.ide;


/**
 * Use this class to register ide components.
 */
public class LPDSLIdeModule extends AbstractLPDSLIdeModule {
}
