/*
 * generated by Xtext 2.23.0.M3
 */
package org.xtext.example.landingpagedsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractLPDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.example.landingpagedsl.lPDSL.LPDSLPackage.eINSTANCE);
		return result;
	}
}
