/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.landingpagedsl.lPDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contact Information</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.landingpagedsl.lPDSL.LPDSLPackage#getContactInformation()
 * @model
 * @generated
 */
public interface ContactInformation extends Sections
{
} // ContactInformation
