/**
 * generated by Xtext 2.23.0.M3
 */
package org.xtext.example.landingpagedsl.lPDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.landingpagedsl.lPDSL.LPDSLPackage
 * @generated
 */
public interface LPDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LPDSLFactory eINSTANCE = org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Landing Page</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Landing Page</em>'.
   * @generated
   */
  LandingPage createLandingPage();

  /**
   * Returns a new object of class '<em>Page Component</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Page Component</em>'.
   * @generated
   */
  PageComponent createPageComponent();

  /**
   * Returns a new object of class '<em>Page Footer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Page Footer</em>'.
   * @generated
   */
  PageFooter createPageFooter();

  /**
   * Returns a new object of class '<em>Link Item</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Link Item</em>'.
   * @generated
   */
  LinkItem createLinkItem();

  /**
   * Returns a new object of class '<em>URL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>URL</em>'.
   * @generated
   */
  URL createURL();

  /**
   * Returns a new object of class '<em>Page Header</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Page Header</em>'.
   * @generated
   */
  PageHeader createPageHeader();

  /**
   * Returns a new object of class '<em>Tab Items</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tab Items</em>'.
   * @generated
   */
  TabItems createTabItems();

  /**
   * Returns a new object of class '<em>Page Body</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Page Body</em>'.
   * @generated
   */
  PageBody createPageBody();

  /**
   * Returns a new object of class '<em>Sections</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sections</em>'.
   * @generated
   */
  Sections createSections();

  /**
   * Returns a new object of class '<em>Resume</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Resume</em>'.
   * @generated
   */
  Resume createResume();

  /**
   * Returns a new object of class '<em>Items</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Items</em>'.
   * @generated
   */
  Items createItems();

  /**
   * Returns a new object of class '<em>Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Description</em>'.
   * @generated
   */
  Description createDescription();

  /**
   * Returns a new object of class '<em>About Me</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>About Me</em>'.
   * @generated
   */
  AboutMe createAboutMe();

  /**
   * Returns a new object of class '<em>Picture</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Picture</em>'.
   * @generated
   */
  Picture createPicture();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  LPDSLPackage getLPDSLPackage();

} //LPDSLFactory
