/**
 * generated by Xtext 2.23.0.M3
 */
package org.xtext.example.landingpagedsl.lPDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.landingpagedsl.lPDSL.LPDSLFactory
 * @model kind="package"
 * @generated
 */
public interface LPDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "lPDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/landingpagedsl/LPDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "lPDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LPDSLPackage eINSTANCE = org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.LandingPageImpl <em>Landing Page</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LandingPageImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getLandingPage()
   * @generated
   */
  int LANDING_PAGE = 0;

  /**
   * The feature id for the '<em><b>Pagecomponent</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANDING_PAGE__PAGECOMPONENT = 0;

  /**
   * The number of structural features of the '<em>Landing Page</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANDING_PAGE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.PageComponentImpl <em>Page Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.PageComponentImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getPageComponent()
   * @generated
   */
  int PAGE_COMPONENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_COMPONENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Page Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_COMPONENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.SectionsImpl <em>Sections</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.SectionsImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getSections()
   * @generated
   */
  int SECTIONS = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTIONS__NAME = 0;

  /**
   * The number of structural features of the '<em>Sections</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTIONS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.PictureCarouselImpl <em>Picture Carousel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.PictureCarouselImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getPictureCarousel()
   * @generated
   */
  int PICTURE_CAROUSEL = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PICTURE_CAROUSEL__NAME = SECTIONS__NAME;

  /**
   * The feature id for the '<em><b>Timer</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PICTURE_CAROUSEL__TIMER = SECTIONS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Picture</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PICTURE_CAROUSEL__PICTURE = SECTIONS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Picture Carousel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PICTURE_CAROUSEL_FEATURE_COUNT = SECTIONS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.PageFooterImpl <em>Page Footer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.PageFooterImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getPageFooter()
   * @generated
   */
  int PAGE_FOOTER = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_FOOTER__NAME = PAGE_COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Links</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_FOOTER__LINKS = PAGE_COMPONENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Page Footer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_FOOTER_FEATURE_COUNT = PAGE_COMPONENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.LinkItemImpl <em>Link Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LinkItemImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getLinkItem()
   * @generated
   */
  int LINK_ITEM = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK_ITEM__NAME = 0;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK_ITEM__TEXT = 1;

  /**
   * The feature id for the '<em><b>Link</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK_ITEM__LINK = 2;

  /**
   * The number of structural features of the '<em>Link Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK_ITEM_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.URLImpl <em>URL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.URLImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getURL()
   * @generated
   */
  int URL = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int URL__NAME = 0;

  /**
   * The feature id for the '<em><b>Path</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int URL__PATH = 1;

  /**
   * The number of structural features of the '<em>URL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int URL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.QualifiedPathImpl <em>Qualified Path</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.QualifiedPathImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getQualifiedPath()
   * @generated
   */
  int QUALIFIED_PATH = 6;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUALIFIED_PATH__VALUE = 0;

  /**
   * The number of structural features of the '<em>Qualified Path</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUALIFIED_PATH_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.PageHeaderImpl <em>Page Header</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.PageHeaderImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getPageHeader()
   * @generated
   */
  int PAGE_HEADER = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_HEADER__NAME = PAGE_COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Title</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_HEADER__TITLE = PAGE_COMPONENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Tabs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_HEADER__TABS = PAGE_COMPONENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Page Header</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_HEADER_FEATURE_COUNT = PAGE_COMPONENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.TabItemsImpl <em>Tab Items</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.TabItemsImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getTabItems()
   * @generated
   */
  int TAB_ITEMS = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAB_ITEMS__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAB_ITEMS__DESCRIPTION = 1;

  /**
   * The number of structural features of the '<em>Tab Items</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAB_ITEMS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.PageBodyImpl <em>Page Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.PageBodyImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getPageBody()
   * @generated
   */
  int PAGE_BODY = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_BODY__NAME = PAGE_COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Sections</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_BODY__SECTIONS = PAGE_COMPONENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Page Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_BODY_FEATURE_COUNT = PAGE_COMPONENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.LinksImpl <em>Links</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LinksImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getLinks()
   * @generated
   */
  int LINKS = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINKS__NAME = SECTIONS__NAME;

  /**
   * The feature id for the '<em><b>Links</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINKS__LINKS = SECTIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Links</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINKS_FEATURE_COUNT = SECTIONS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.ContactInformationImpl <em>Contact Information</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.ContactInformationImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getContactInformation()
   * @generated
   */
  int CONTACT_INFORMATION = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTACT_INFORMATION__NAME = SECTIONS__NAME;

  /**
   * The number of structural features of the '<em>Contact Information</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTACT_INFORMATION_FEATURE_COUNT = SECTIONS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.ResumeImpl <em>Resume</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.ResumeImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getResume()
   * @generated
   */
  int RESUME = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESUME__NAME = SECTIONS__NAME;

  /**
   * The feature id for the '<em><b>Resumeitems</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESUME__RESUMEITEMS = SECTIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Resume</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESUME_FEATURE_COUNT = SECTIONS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.ItemsImpl <em>Items</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.ItemsImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getItems()
   * @generated
   */
  int ITEMS = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEMS__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEMS__DESCRIPTION = 1;

  /**
   * The number of structural features of the '<em>Items</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEMS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.DescriptionImpl <em>Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.DescriptionImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getDescription()
   * @generated
   */
  int DESCRIPTION = 15;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__VALUE = 0;

  /**
   * The number of structural features of the '<em>Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.TimeSpecifierImpl <em>Time Specifier</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.TimeSpecifierImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getTimeSpecifier()
   * @generated
   */
  int TIME_SPECIFIER = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_SPECIFIER__NAME = 0;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_SPECIFIER__TIME = 1;

  /**
   * The number of structural features of the '<em>Time Specifier</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_SPECIFIER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.IntegerImpl <em>Integer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.IntegerImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getInteger()
   * @generated
   */
  int INTEGER = 17;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER__VALUE = 0;

  /**
   * The number of structural features of the '<em>Integer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.AboutMeImpl <em>About Me</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.AboutMeImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getAboutMe()
   * @generated
   */
  int ABOUT_ME = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABOUT_ME__NAME = SECTIONS__NAME;

  /**
   * The feature id for the '<em><b>Picture</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABOUT_ME__PICTURE = SECTIONS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABOUT_ME__DESCRIPTION = SECTIONS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>About Me</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABOUT_ME_FEATURE_COUNT = SECTIONS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.PictureImpl <em>Picture</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.PictureImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getPicture()
   * @generated
   */
  int PICTURE = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PICTURE__NAME = 0;

  /**
   * The feature id for the '<em><b>Imagepath</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PICTURE__IMAGEPATH = 1;

  /**
   * The number of structural features of the '<em>Picture</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PICTURE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.ImagePathImpl <em>Image Path</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.ImagePathImpl
   * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getImagePath()
   * @generated
   */
  int IMAGE_PATH = 20;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_PATH__VALUE = 0;

  /**
   * The number of structural features of the '<em>Image Path</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_PATH_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.LandingPage <em>Landing Page</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Landing Page</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.LandingPage
   * @generated
   */
  EClass getLandingPage();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.landingpagedsl.lPDSL.LandingPage#getPagecomponent <em>Pagecomponent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pagecomponent</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.LandingPage#getPagecomponent()
   * @see #getLandingPage()
   * @generated
   */
  EReference getLandingPage_Pagecomponent();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.PageComponent <em>Page Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Page Component</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.PageComponent
   * @generated
   */
  EClass getPageComponent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.landingpagedsl.lPDSL.PageComponent#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.PageComponent#getName()
   * @see #getPageComponent()
   * @generated
   */
  EAttribute getPageComponent_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.PictureCarousel <em>Picture Carousel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Picture Carousel</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.PictureCarousel
   * @generated
   */
  EClass getPictureCarousel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.landingpagedsl.lPDSL.PictureCarousel#getTimer <em>Timer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Timer</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.PictureCarousel#getTimer()
   * @see #getPictureCarousel()
   * @generated
   */
  EReference getPictureCarousel_Timer();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.landingpagedsl.lPDSL.PictureCarousel#getPicture <em>Picture</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Picture</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.PictureCarousel#getPicture()
   * @see #getPictureCarousel()
   * @generated
   */
  EReference getPictureCarousel_Picture();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.PageFooter <em>Page Footer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Page Footer</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.PageFooter
   * @generated
   */
  EClass getPageFooter();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.landingpagedsl.lPDSL.PageFooter#getLinks <em>Links</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Links</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.PageFooter#getLinks()
   * @see #getPageFooter()
   * @generated
   */
  EReference getPageFooter_Links();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.LinkItem <em>Link Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Link Item</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.LinkItem
   * @generated
   */
  EClass getLinkItem();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.landingpagedsl.lPDSL.LinkItem#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.LinkItem#getName()
   * @see #getLinkItem()
   * @generated
   */
  EAttribute getLinkItem_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.landingpagedsl.lPDSL.LinkItem#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Text</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.LinkItem#getText()
   * @see #getLinkItem()
   * @generated
   */
  EReference getLinkItem_Text();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.landingpagedsl.lPDSL.LinkItem#getLink <em>Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Link</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.LinkItem#getLink()
   * @see #getLinkItem()
   * @generated
   */
  EReference getLinkItem_Link();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.URL <em>URL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>URL</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.URL
   * @generated
   */
  EClass getURL();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.landingpagedsl.lPDSL.URL#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.URL#getName()
   * @see #getURL()
   * @generated
   */
  EAttribute getURL_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.landingpagedsl.lPDSL.URL#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Path</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.URL#getPath()
   * @see #getURL()
   * @generated
   */
  EReference getURL_Path();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.QualifiedPath <em>Qualified Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Qualified Path</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.QualifiedPath
   * @generated
   */
  EClass getQualifiedPath();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.landingpagedsl.lPDSL.QualifiedPath#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.QualifiedPath#getValue()
   * @see #getQualifiedPath()
   * @generated
   */
  EAttribute getQualifiedPath_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.PageHeader <em>Page Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Page Header</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.PageHeader
   * @generated
   */
  EClass getPageHeader();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.landingpagedsl.lPDSL.PageHeader#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Title</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.PageHeader#getTitle()
   * @see #getPageHeader()
   * @generated
   */
  EReference getPageHeader_Title();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.landingpagedsl.lPDSL.PageHeader#getTabs <em>Tabs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tabs</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.PageHeader#getTabs()
   * @see #getPageHeader()
   * @generated
   */
  EReference getPageHeader_Tabs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.TabItems <em>Tab Items</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tab Items</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.TabItems
   * @generated
   */
  EClass getTabItems();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.landingpagedsl.lPDSL.TabItems#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.TabItems#getName()
   * @see #getTabItems()
   * @generated
   */
  EAttribute getTabItems_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.landingpagedsl.lPDSL.TabItems#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Description</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.TabItems#getDescription()
   * @see #getTabItems()
   * @generated
   */
  EReference getTabItems_Description();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.PageBody <em>Page Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Page Body</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.PageBody
   * @generated
   */
  EClass getPageBody();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.landingpagedsl.lPDSL.PageBody#getSections <em>Sections</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sections</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.PageBody#getSections()
   * @see #getPageBody()
   * @generated
   */
  EReference getPageBody_Sections();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.Sections <em>Sections</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sections</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.Sections
   * @generated
   */
  EClass getSections();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.landingpagedsl.lPDSL.Sections#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.Sections#getName()
   * @see #getSections()
   * @generated
   */
  EAttribute getSections_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.Links <em>Links</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Links</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.Links
   * @generated
   */
  EClass getLinks();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.landingpagedsl.lPDSL.Links#getLinks <em>Links</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Links</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.Links#getLinks()
   * @see #getLinks()
   * @generated
   */
  EReference getLinks_Links();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.ContactInformation <em>Contact Information</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Contact Information</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.ContactInformation
   * @generated
   */
  EClass getContactInformation();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.Resume <em>Resume</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Resume</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.Resume
   * @generated
   */
  EClass getResume();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.landingpagedsl.lPDSL.Resume#getResumeitems <em>Resumeitems</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Resumeitems</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.Resume#getResumeitems()
   * @see #getResume()
   * @generated
   */
  EReference getResume_Resumeitems();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.Items <em>Items</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Items</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.Items
   * @generated
   */
  EClass getItems();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.landingpagedsl.lPDSL.Items#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.Items#getName()
   * @see #getItems()
   * @generated
   */
  EAttribute getItems_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.landingpagedsl.lPDSL.Items#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Description</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.Items#getDescription()
   * @see #getItems()
   * @generated
   */
  EReference getItems_Description();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.Description <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Description</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.Description
   * @generated
   */
  EClass getDescription();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.landingpagedsl.lPDSL.Description#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.Description#getValue()
   * @see #getDescription()
   * @generated
   */
  EAttribute getDescription_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.TimeSpecifier <em>Time Specifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time Specifier</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.TimeSpecifier
   * @generated
   */
  EClass getTimeSpecifier();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.landingpagedsl.lPDSL.TimeSpecifier#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.TimeSpecifier#getName()
   * @see #getTimeSpecifier()
   * @generated
   */
  EAttribute getTimeSpecifier_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.landingpagedsl.lPDSL.TimeSpecifier#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Time</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.TimeSpecifier#getTime()
   * @see #getTimeSpecifier()
   * @generated
   */
  EReference getTimeSpecifier_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.Integer <em>Integer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Integer</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.Integer
   * @generated
   */
  EClass getInteger();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.landingpagedsl.lPDSL.Integer#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.Integer#getValue()
   * @see #getInteger()
   * @generated
   */
  EAttribute getInteger_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.AboutMe <em>About Me</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>About Me</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.AboutMe
   * @generated
   */
  EClass getAboutMe();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.landingpagedsl.lPDSL.AboutMe#getPicture <em>Picture</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Picture</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.AboutMe#getPicture()
   * @see #getAboutMe()
   * @generated
   */
  EReference getAboutMe_Picture();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.landingpagedsl.lPDSL.AboutMe#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Description</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.AboutMe#getDescription()
   * @see #getAboutMe()
   * @generated
   */
  EReference getAboutMe_Description();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.Picture <em>Picture</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Picture</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.Picture
   * @generated
   */
  EClass getPicture();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.landingpagedsl.lPDSL.Picture#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.Picture#getName()
   * @see #getPicture()
   * @generated
   */
  EAttribute getPicture_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.landingpagedsl.lPDSL.Picture#getImagepath <em>Imagepath</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imagepath</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.Picture#getImagepath()
   * @see #getPicture()
   * @generated
   */
  EReference getPicture_Imagepath();

  /**
   * Returns the meta object for class '{@link org.xtext.example.landingpagedsl.lPDSL.ImagePath <em>Image Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Image Path</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.ImagePath
   * @generated
   */
  EClass getImagePath();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.landingpagedsl.lPDSL.ImagePath#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.landingpagedsl.lPDSL.ImagePath#getValue()
   * @see #getImagePath()
   * @generated
   */
  EAttribute getImagePath_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LPDSLFactory getLPDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.LandingPageImpl <em>Landing Page</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LandingPageImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getLandingPage()
     * @generated
     */
    EClass LANDING_PAGE = eINSTANCE.getLandingPage();

    /**
     * The meta object literal for the '<em><b>Pagecomponent</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LANDING_PAGE__PAGECOMPONENT = eINSTANCE.getLandingPage_Pagecomponent();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.PageComponentImpl <em>Page Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.PageComponentImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getPageComponent()
     * @generated
     */
    EClass PAGE_COMPONENT = eINSTANCE.getPageComponent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAGE_COMPONENT__NAME = eINSTANCE.getPageComponent_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.PictureCarouselImpl <em>Picture Carousel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.PictureCarouselImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getPictureCarousel()
     * @generated
     */
    EClass PICTURE_CAROUSEL = eINSTANCE.getPictureCarousel();

    /**
     * The meta object literal for the '<em><b>Timer</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PICTURE_CAROUSEL__TIMER = eINSTANCE.getPictureCarousel_Timer();

    /**
     * The meta object literal for the '<em><b>Picture</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PICTURE_CAROUSEL__PICTURE = eINSTANCE.getPictureCarousel_Picture();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.PageFooterImpl <em>Page Footer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.PageFooterImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getPageFooter()
     * @generated
     */
    EClass PAGE_FOOTER = eINSTANCE.getPageFooter();

    /**
     * The meta object literal for the '<em><b>Links</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAGE_FOOTER__LINKS = eINSTANCE.getPageFooter_Links();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.LinkItemImpl <em>Link Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LinkItemImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getLinkItem()
     * @generated
     */
    EClass LINK_ITEM = eINSTANCE.getLinkItem();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINK_ITEM__NAME = eINSTANCE.getLinkItem_Name();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINK_ITEM__TEXT = eINSTANCE.getLinkItem_Text();

    /**
     * The meta object literal for the '<em><b>Link</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINK_ITEM__LINK = eINSTANCE.getLinkItem_Link();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.URLImpl <em>URL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.URLImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getURL()
     * @generated
     */
    EClass URL = eINSTANCE.getURL();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute URL__NAME = eINSTANCE.getURL_Name();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference URL__PATH = eINSTANCE.getURL_Path();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.QualifiedPathImpl <em>Qualified Path</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.QualifiedPathImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getQualifiedPath()
     * @generated
     */
    EClass QUALIFIED_PATH = eINSTANCE.getQualifiedPath();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUALIFIED_PATH__VALUE = eINSTANCE.getQualifiedPath_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.PageHeaderImpl <em>Page Header</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.PageHeaderImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getPageHeader()
     * @generated
     */
    EClass PAGE_HEADER = eINSTANCE.getPageHeader();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAGE_HEADER__TITLE = eINSTANCE.getPageHeader_Title();

    /**
     * The meta object literal for the '<em><b>Tabs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAGE_HEADER__TABS = eINSTANCE.getPageHeader_Tabs();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.TabItemsImpl <em>Tab Items</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.TabItemsImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getTabItems()
     * @generated
     */
    EClass TAB_ITEMS = eINSTANCE.getTabItems();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TAB_ITEMS__NAME = eINSTANCE.getTabItems_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TAB_ITEMS__DESCRIPTION = eINSTANCE.getTabItems_Description();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.PageBodyImpl <em>Page Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.PageBodyImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getPageBody()
     * @generated
     */
    EClass PAGE_BODY = eINSTANCE.getPageBody();

    /**
     * The meta object literal for the '<em><b>Sections</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAGE_BODY__SECTIONS = eINSTANCE.getPageBody_Sections();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.SectionsImpl <em>Sections</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.SectionsImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getSections()
     * @generated
     */
    EClass SECTIONS = eINSTANCE.getSections();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SECTIONS__NAME = eINSTANCE.getSections_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.LinksImpl <em>Links</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LinksImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getLinks()
     * @generated
     */
    EClass LINKS = eINSTANCE.getLinks();

    /**
     * The meta object literal for the '<em><b>Links</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINKS__LINKS = eINSTANCE.getLinks_Links();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.ContactInformationImpl <em>Contact Information</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.ContactInformationImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getContactInformation()
     * @generated
     */
    EClass CONTACT_INFORMATION = eINSTANCE.getContactInformation();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.ResumeImpl <em>Resume</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.ResumeImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getResume()
     * @generated
     */
    EClass RESUME = eINSTANCE.getResume();

    /**
     * The meta object literal for the '<em><b>Resumeitems</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESUME__RESUMEITEMS = eINSTANCE.getResume_Resumeitems();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.ItemsImpl <em>Items</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.ItemsImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getItems()
     * @generated
     */
    EClass ITEMS = eINSTANCE.getItems();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ITEMS__NAME = eINSTANCE.getItems_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ITEMS__DESCRIPTION = eINSTANCE.getItems_Description();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.DescriptionImpl <em>Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.DescriptionImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getDescription()
     * @generated
     */
    EClass DESCRIPTION = eINSTANCE.getDescription();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESCRIPTION__VALUE = eINSTANCE.getDescription_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.TimeSpecifierImpl <em>Time Specifier</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.TimeSpecifierImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getTimeSpecifier()
     * @generated
     */
    EClass TIME_SPECIFIER = eINSTANCE.getTimeSpecifier();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_SPECIFIER__NAME = eINSTANCE.getTimeSpecifier_Name();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TIME_SPECIFIER__TIME = eINSTANCE.getTimeSpecifier_Time();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.IntegerImpl <em>Integer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.IntegerImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getInteger()
     * @generated
     */
    EClass INTEGER = eINSTANCE.getInteger();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTEGER__VALUE = eINSTANCE.getInteger_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.AboutMeImpl <em>About Me</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.AboutMeImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getAboutMe()
     * @generated
     */
    EClass ABOUT_ME = eINSTANCE.getAboutMe();

    /**
     * The meta object literal for the '<em><b>Picture</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABOUT_ME__PICTURE = eINSTANCE.getAboutMe_Picture();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABOUT_ME__DESCRIPTION = eINSTANCE.getAboutMe_Description();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.PictureImpl <em>Picture</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.PictureImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getPicture()
     * @generated
     */
    EClass PICTURE = eINSTANCE.getPicture();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PICTURE__NAME = eINSTANCE.getPicture_Name();

    /**
     * The meta object literal for the '<em><b>Imagepath</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PICTURE__IMAGEPATH = eINSTANCE.getPicture_Imagepath();

    /**
     * The meta object literal for the '{@link org.xtext.example.landingpagedsl.lPDSL.impl.ImagePathImpl <em>Image Path</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.ImagePathImpl
     * @see org.xtext.example.landingpagedsl.lPDSL.impl.LPDSLPackageImpl#getImagePath()
     * @generated
     */
    EClass IMAGE_PATH = eINSTANCE.getImagePath();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMAGE_PATH__VALUE = eINSTANCE.getImagePath_Value();

  }

} //LPDSLPackage
