/*
 * generated by Xtext 2.23.0.M3
 */
package org.xtext.example.landingpagedsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LPDSLUiModule extends AbstractLPDSLUiModule {

	public LPDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
