/*
 * generated by Xtext 2.23.0.M3
 */
package org.xtext.example.landingpagedsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.landingpagedsl.lPDSL.AboutMe;
import org.xtext.example.landingpagedsl.lPDSL.Description;
import org.xtext.example.landingpagedsl.lPDSL.ImagePath;
import org.xtext.example.landingpagedsl.lPDSL.Items;
import org.xtext.example.landingpagedsl.lPDSL.LPDSLPackage;
import org.xtext.example.landingpagedsl.lPDSL.LandingPage;
import org.xtext.example.landingpagedsl.lPDSL.LinkItem;
import org.xtext.example.landingpagedsl.lPDSL.PageBody;
import org.xtext.example.landingpagedsl.lPDSL.PageFooter;
import org.xtext.example.landingpagedsl.lPDSL.PageHeader;
import org.xtext.example.landingpagedsl.lPDSL.Picture;
import org.xtext.example.landingpagedsl.lPDSL.QualifiedPath;
import org.xtext.example.landingpagedsl.lPDSL.Resume;
import org.xtext.example.landingpagedsl.lPDSL.TabItems;
import org.xtext.example.landingpagedsl.lPDSL.URL;
import org.xtext.example.landingpagedsl.services.LPDSLGrammarAccess;

@SuppressWarnings("all")
public class LPDSLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private LPDSLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == LPDSLPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case LPDSLPackage.ABOUT_ME:
				sequence_AboutMe(context, (AboutMe) semanticObject); 
				return; 
			case LPDSLPackage.DESCRIPTION:
				sequence_Description(context, (Description) semanticObject); 
				return; 
			case LPDSLPackage.IMAGE_PATH:
				sequence_ImagePath(context, (ImagePath) semanticObject); 
				return; 
			case LPDSLPackage.ITEMS:
				sequence_Items(context, (Items) semanticObject); 
				return; 
			case LPDSLPackage.LANDING_PAGE:
				sequence_LandingPage(context, (LandingPage) semanticObject); 
				return; 
			case LPDSLPackage.LINK_ITEM:
				sequence_LinkItem(context, (LinkItem) semanticObject); 
				return; 
			case LPDSLPackage.PAGE_BODY:
				sequence_PageBody(context, (PageBody) semanticObject); 
				return; 
			case LPDSLPackage.PAGE_FOOTER:
				sequence_PageFooter(context, (PageFooter) semanticObject); 
				return; 
			case LPDSLPackage.PAGE_HEADER:
				sequence_PageHeader(context, (PageHeader) semanticObject); 
				return; 
			case LPDSLPackage.PICTURE:
				sequence_Picture(context, (Picture) semanticObject); 
				return; 
			case LPDSLPackage.QUALIFIED_PATH:
				sequence_QualifiedPath(context, (QualifiedPath) semanticObject); 
				return; 
			case LPDSLPackage.RESUME:
				sequence_Resume(context, (Resume) semanticObject); 
				return; 
			case LPDSLPackage.TAB_ITEMS:
				sequence_TabItems(context, (TabItems) semanticObject); 
				return; 
			case LPDSLPackage.URL:
				sequence_URL(context, (URL) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Sections returns AboutMe
	 *     AboutMe returns AboutMe
	 *
	 * Constraint:
	 *     (name=ID picture+=Picture description+=Items)
	 */
	protected void sequence_AboutMe(ISerializationContext context, AboutMe semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Description returns Description
	 *
	 * Constraint:
	 *     value=STRING
	 */
	protected void sequence_Description(ISerializationContext context, Description semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, LPDSLPackage.Literals.DESCRIPTION__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LPDSLPackage.Literals.DESCRIPTION__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDescriptionAccess().getValueSTRINGTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ImagePath returns ImagePath
	 *
	 * Constraint:
	 *     value=STRING
	 */
	protected void sequence_ImagePath(ISerializationContext context, ImagePath semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, LPDSLPackage.Literals.IMAGE_PATH__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LPDSLPackage.Literals.IMAGE_PATH__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getImagePathAccess().getValueSTRINGTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Items returns Items
	 *
	 * Constraint:
	 *     (name=ID description+=Description)
	 */
	protected void sequence_Items(ISerializationContext context, Items semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     LandingPage returns LandingPage
	 *
	 * Constraint:
	 *     pagecomponent+=PageComponent+
	 */
	protected void sequence_LandingPage(ISerializationContext context, LandingPage semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     LinkItem returns LinkItem
	 *
	 * Constraint:
	 *     (name=ID text+=Items link+=URL)
	 */
	protected void sequence_LinkItem(ISerializationContext context, LinkItem semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     PageComponent returns PageBody
	 *     PageBody returns PageBody
	 *
	 * Constraint:
	 *     (name=ID sections+=Sections*)
	 */
	protected void sequence_PageBody(ISerializationContext context, PageBody semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     PageComponent returns PageFooter
	 *     PageFooter returns PageFooter
	 *
	 * Constraint:
	 *     (name=ID links+=LinkItem*)
	 */
	protected void sequence_PageFooter(ISerializationContext context, PageFooter semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     PageComponent returns PageHeader
	 *     PageHeader returns PageHeader
	 *
	 * Constraint:
	 *     (name=ID title+=Items tabs+=TabItems*)
	 */
	protected void sequence_PageHeader(ISerializationContext context, PageHeader semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Picture returns Picture
	 *
	 * Constraint:
	 *     (name=ID imagepath+=ImagePath)
	 */
	protected void sequence_Picture(ISerializationContext context, Picture semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     QualifiedPath returns QualifiedPath
	 *
	 * Constraint:
	 *     value=STRING
	 */
	protected void sequence_QualifiedPath(ISerializationContext context, QualifiedPath semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, LPDSLPackage.Literals.QUALIFIED_PATH__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LPDSLPackage.Literals.QUALIFIED_PATH__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getQualifiedPathAccess().getValueSTRINGTerminalRuleCall_0_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Sections returns Resume
	 *     Resume returns Resume
	 *
	 * Constraint:
	 *     (name=ID resumeitems+=Items*)
	 */
	protected void sequence_Resume(ISerializationContext context, Resume semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     TabItems returns TabItems
	 *
	 * Constraint:
	 *     (name=ID description+=Description)
	 */
	protected void sequence_TabItems(ISerializationContext context, TabItems semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     URL returns URL
	 *
	 * Constraint:
	 *     (name=ID path+=QualifiedPath)
	 */
	protected void sequence_URL(ISerializationContext context, URL semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
