/*
 * generated by Xtext 2.23.0.M3
 */
package org.xtext.example.landingpagedsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.landingpagedsl.parser.antlr.internal.InternalLPDSLParser;
import org.xtext.example.landingpagedsl.services.LPDSLGrammarAccess;

public class LPDSLParser extends AbstractAntlrParser {

	@Inject
	private LPDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLPDSLParser createParser(XtextTokenStream stream) {
		return new InternalLPDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "LandingPage";
	}

	public LPDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LPDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
